### ISSUE TITLE
Health charging

### ISSUE THREAD

**Issue by Baldomo** [aredden/G14ControlR3#4]
On the G14 the health charging can be enabled with the following Powershell command (with elevated privileges) where `X` is an integer between 0 and 100:
```powershell
(Get-WmiObject -Namespace root/WMI -Class AsusAtkWmi_WMNB).DEVS(0x00120057, X)
```
Note: the command has to be executed after boot AND whenever resuming from sleep.
Could this be implemented in g14controlR3 by any chance?

**Comment by aredden** [comment]
Well it could but I'm not working on this anymore. I actually have that implemented in my new repo. I really hated this project and decided to give it an overhaul. I just started releasing yesterday https://github.com/aredden/electron-G14Control/releases

**Comment by Baldomo** [comment]
Very nice! Thank you for releasing it. How's the RAM usage though? I generally dislike electron based apps because they boggle up RAM like no others

**Comment by aredden** [comment]
It does use a bit of ram. Usually only about 250mb, which (if 16gb of ram) will only be about 1.5% of total. I don't think it's too bad, but I know some might feel differently.
