### ISSUE TITLE
Windows 11: ValueError: invalid literal for int() with base 10: ‘KNOWN’

### ISSUE THREAD

**Issue by fscottcopeland** [aredden/G14ControlR3#8]
Getting this issue when starting up the program now. This has only become a thing since I upgraded to Windows 11.

File
“C:\Users\alexa\Documents\G14ControlR3\venv\lib\site-packages\pystray\_base.py’, line 393, in checked
File "G14Control.pyw’, line 328, in <lambda>
ValueError: invalid literal for int() with base 10: ‘KNOWN’

**Comment by aredden** [comment]
I have no idea. I only tried g14controlv2 for this on windows 11, the electron version. Also, I don't actively develop this anymore so there might be issues. https://github.com/aredden/electron-g14control

**Comment by fscottcopeland** [comment]
Ah @aredden fair enough, thanks for getting back to me. Are you still actively developing the electron version?
